spring:
  application:
    name: demo


  datasource:
    url: jdbc:sqlserver://192.168.122.2:1433;databaseName=F2Database;encrypt=false;trustServerCertificate=true
    username: kproduct
    password: Tanphat@02032013
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 40
      minimum-idle: 5
      idle-timeout: 30000  # 30s không dùng thì trả connection về pool
      max-lifetime: 1800000  # 30 phút reset connection
      connection-timeout: 5000  # 5s timeout nếu không lấy được connection

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  address: 0.0.0.0
  port: 8080